### ISSUE TITLE
PHPLab - TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/PHPLab#6]
PHPLab

**関連管理**
https://github.com/youbinoyou/KaraageChannel/issues/10

作業について

**作業：アップロード**
- [ ] 【アップロード】 ver 1.0.0

**作業：PHPLab**
- [x] TODO作成 #81
- [ ] TODO整理
- [x] はじめに #17
- [ ] API xml http://blog.kamabokonet.com/2013/04/30/phpを用いて3行でapiを作る！！/
- [ ] API JSON http://dot-town-lab.com/laboratory/item/24
- [ ] CSV http://dot-town-lab.com/laboratory/item/19

**作業：コーディング**
- [ ] コーディング

**作業：管理**
- [ ] 清算管理
- [ ] 権利管理
